travis:
  secure:
    BINSTAR_TOKEN: OTEMBMi6AUzuyvvTnwCVsQkmJqR/KPBwkLFJkbWq3J3QlP2k9fyd37VxBwA67XhPl/omZRJK21uGEocNF/m+5g4BwNQXZpaTiEHIut/m4wrQZh0vtvMTJANLZZYWEarU9SpNhido39aOZl9FNVACMhQ33ZFMtwkjrnw5To5M1wtngAhfUEaRsbiAnHcVZkjz3Ky7dVXQ9Zj+vNo+NtVAhLjS+6pCMIDcSTWcPNNVt0s97YVFlFrqyKDI12XSeir5XEcricJnUyv9YCtE8hLQZkZL7EgF1nXhaajPKooFYb2UR2+vNJjd/HqfTM3ybALK6rR66atizbL4vQT7LBbAgEctyLPgd2oKLYL1C/pJ797mtsGwaD+DoxdyCi+SLGlDjiuNE44+e69QiDMuJ4FLNLjxYqEsfkAaqD6cGvQAVNA9c6ptgYcGtaJnkD7CxSHiaAQ63kt36JYT+N1qgeaUhdHbE61u1bf/eJlK0b+9rsB8jTNWtiHT5u3aVX45SMIe4+IJkJFGljomE30uQD7FrDLPr/z6z0W4JSUWe0XHkgdwRUyj7HB/lNJGOavJx9X3BcCHa3XtxF/EyCgFEbuNj17fuZKB9a7Yhjs28/P4sFmri2m7VC5DSw/3/tVfOdAHDm5Jg7NDLJSDNgRM3LlzCdIvjwetPAOwv338wh8nVqs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
